import type { GenerateConfig } from '@apiforge/shared';

export function usersCreateSql(config: GenerateConfig): string {
  const table = config.auth.tableName || 'users';
  const userCol = config.auth.usernameColumn || 'username';
  const passCol = config.auth.passwordColumn || 'password';
  const idCol = config.auth.idColumn || 'id';

  switch (config.connection.engine) {
    case 'postgresql':
      return `-- Generated by ApiForge
CREATE TABLE IF NOT EXISTS ${table} (
  ${idCol} SERIAL PRIMARY KEY,
  ${userCol} VARCHAR(255) NOT NULL UNIQUE,
  ${passCol} VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
`;
    case 'mysql':
      return `-- Generated by ApiForge
CREATE TABLE IF NOT EXISTS \`${table}\` (
  \`${idCol}\` INT AUTO_INCREMENT PRIMARY KEY,
  \`${userCol}\` VARCHAR(255) NOT NULL UNIQUE,
  \`${passCol}\` VARCHAR(255) NOT NULL,
  \`created_at\` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`;
    case 'sqlserver':
      return `-- Generated by ApiForge
IF OBJECT_ID(N'dbo.${table}', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.${table} (
    ${idCol} INT IDENTITY(1,1) PRIMARY KEY,
    ${userCol} NVARCHAR(255) NOT NULL UNIQUE,
    ${passCol} NVARCHAR(255) NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
END
`;
    case 'sqlite':
      return `-- Generated by ApiForge
CREATE TABLE IF NOT EXISTS ${table} (
  ${idCol} INTEGER PRIMARY KEY AUTOINCREMENT,
  ${userCol} TEXT NOT NULL UNIQUE,
  ${passCol} TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
`;
    default:
      throw new Error(`Unsupported engine: ${config.connection.engine}`);
  }
}

export function authSqlFile(config: GenerateConfig): { path: string; content: string; language: 'sql' } | null {
  if (!config.auth.enabled || config.auth.mode !== 'create') return null;
  return {
    path: 'sql/create-users.sql',
    content: usersCreateSql(config),
    language: 'sql',
  };
}
