import type { ColumnMeta, DbEngine, GenerateConfig, GeneratedFile, TableMeta } from '@apiforge/shared';
import { kebabCase, selectedTables } from '../helpers.js';

function columnSql(col: ColumnMeta, engine: DbEngine): string {
  const type = col.dataType || 'TEXT';
  const nullSql = col.isNullable && !col.isPrimaryKey ? '' : ' NOT NULL';
  const uniqueSql = col.isUnique && !col.isPrimaryKey ? ' UNIQUE' : '';

  if (col.isPrimaryKey) {
    switch (engine) {
      case 'postgresql':
        if (/serial/i.test(type)) return `${col.name} ${type} PRIMARY KEY`;
        return `${col.name} ${type} PRIMARY KEY`;
      case 'mysql':
        return `\`${col.name}\` ${type} PRIMARY KEY`;
      case 'sqlserver':
        return `${col.name} ${type} PRIMARY KEY`;
      case 'sqlite':
        if (/integer/i.test(type)) return `${col.name} INTEGER PRIMARY KEY AUTOINCREMENT`;
        return `${col.name} ${type} PRIMARY KEY`;
      default:
        return `${col.name} ${type} PRIMARY KEY`;
    }
  }

  switch (engine) {
    case 'mysql':
      return `\`${col.name}\` ${type}${nullSql}${uniqueSql}`;
    default:
      return `${col.name} ${type}${nullSql}${uniqueSql}`;
  }
}

export function designedTableCreateSql(table: TableMeta, engine: DbEngine): string {
  const cols = table.columns.filter((c) => c.selected !== false);
  const lines = cols.map((c) => `  ${columnSql(c, engine)}`);

  switch (engine) {
    case 'postgresql':
      return `-- Generated by ApiForge (designed table)
CREATE TABLE IF NOT EXISTS ${table.name} (
${lines.join(',\n')}
);
`;
    case 'mysql':
      return `-- Generated by ApiForge (designed table)
CREATE TABLE IF NOT EXISTS \`${table.name}\` (
${lines.join(',\n')}
);
`;
    case 'sqlserver': {
      const schema = table.schema && table.schema !== 'main' ? table.schema : 'dbo';
      return `-- Generated by ApiForge (designed table)
IF OBJECT_ID(N'${schema}.${table.name}', N'U') IS NULL
BEGIN
  CREATE TABLE ${schema}.${table.name} (
${lines.join(',\n')}
  );
END
`;
    }
    case 'sqlite':
      return `-- Generated by ApiForge (designed table)
CREATE TABLE IF NOT EXISTS ${table.name} (
${lines.join(',\n')}
);
`;
    default:
      throw new Error(`Unsupported engine: ${engine}`);
  }
}

export function designedTableSqlFiles(config: GenerateConfig): GeneratedFile[] {
  const engine = config.connection.engine;
  return selectedTables(config)
    .filter((t) => t.source === 'designed')
    .map((t) => ({
      path: `sql/create-${kebabCase(t.name)}.sql`,
      content: designedTableCreateSql(t, engine),
      language: 'sql' as const,
    }));
}
