import type { GenerateConfig, GeneratedFile } from '@apiforge/shared';

function connectionLine(config: GenerateConfig): string {
  const c = config.connection;
  if (c.connectionString) {
    return `DATABASE_URL=${c.connectionString}`;
  }
  switch (c.engine) {
    case 'postgresql':
      return `DATABASE_URL=postgresql://${c.username || 'postgres'}:${c.password || 'password'}@${c.host || 'localhost'}:${c.port || 5432}/${c.database || 'mydb'}`;
    case 'mysql':
      return `DATABASE_URL=mysql://${c.username || 'root'}:${c.password || 'password'}@${c.host || 'localhost'}:${c.port || 3306}/${c.database || 'mydb'}`;
    case 'sqlserver':
      return `DATABASE_URL=Server=${c.host || 'localhost'},${c.port || 1433};Database=${c.database || 'mydb'};User Id=${c.username || 'sa'};Password=${c.password || 'Your_password123'};TrustServerCertificate=True`;
    case 'sqlite':
      return `DATABASE_URL=${c.filePath || './data/app.db'}`;
  }
}

export function envExample(config: GenerateConfig): GeneratedFile {
  const lines = [
    '# Generated by ApiForge — copy to .env and adjust values',
    `PORT=${config.port}`,
    connectionLine(config),
    `DB_ENGINE=${config.connection.engine}`,
  ];

  if (config.auth.enabled) {
    lines.push(
      `JWT_SECRET=${config.auth.jwtSecret || 'change-me-to-a-long-random-secret'}`,
      `JWT_EXPIRES_IN=${config.auth.jwtExpiresIn || '24h'}`,
    );
  }

  const sec = config.security;
  lines.push(
    `CORS_MODE=${sec.corsMode}`,
    `CORS_ORIGINS=${sec.corsOrigins.join(',')}`,
    `ALLOWED_IPS=${sec.allowedIps.join(',')}`,
    `RATE_LIMIT_ENABLED=${sec.rateLimitEnabled}`,
    `RATE_LIMIT_PER_MINUTE=${sec.rateLimitPerMinute}`,
    `API_KEY_ENABLED=${sec.apiKeyEnabled}`,
    `API_KEY_HEADER=${sec.apiKeyHeader}`,
    `API_KEY=change-me-api-key`,
    `HELMET_ENABLED=${sec.helmetEnabled}`,
  );

  return {
    path: '.env.example',
    content: `${lines.join('\n')}\n`,
    language: 'env',
  };
}
