import type { GenerateConfig, GeneratedFile } from '@apiforge/shared';
import { STACK_LABELS, ENGINE_LABELS } from '@apiforge/shared';
import { buildEndpoints } from '../endpoints.js';
import { selectedTables } from '../helpers.js';
import { usersCreateSql } from './auth-sql.js';

export function readmeFile(config: GenerateConfig): GeneratedFile {
  const tables = selectedTables(config);
  const endpoints = buildEndpoints(config);
  const isNode = config.stack.startsWith('node');
  const runCmd = isNode
    ? 'npm install\nnpm run dev'
    : 'dotnet restore\ndotnet run';

  const swaggerPath = isNode ? '/api-docs' : '/swagger';

  const content = `# ${config.projectName}

Generated by **ApiForge** — production-ready CRUD API.

## Stack

| | |
|---|---|
| Runtime | ${STACK_LABELS[config.stack]} |
| Database | ${ENGINE_LABELS[config.connection.engine]} |
| Auth | ${config.auth.enabled ? 'JWT Bearer + bcrypt' : 'Disabled'} |
| Docs | ${config.includeSwagger ? `Swagger at ${swaggerPath}` : 'Off'} |
| Port | ${config.port} |

## Tables

${tables.map((t) => `- \`${t.schema ? `${t.schema}.` : ''}${t.name}\` (${t.columns.length} columns)`).join('\n')}

## Quick start

\`\`\`bash
cp .env.example .env
# edit .env with your database credentials
${runCmd}
\`\`\`

Health: http://localhost:${config.port}/health
${config.includeSwagger ? `Swagger: http://localhost:${config.port}${swaggerPath}` : ''}

## Endpoints

| Method | Path | Auth |
|--------|------|------|
${endpoints.map((e) => `| ${e.method} | \`${e.path}\` | ${e.authRequired ? 'Yes' : 'No'} |`).join('\n')}

## Security

- CORS: **${config.security.corsMode}**
- Rate limit: **${config.security.rateLimitEnabled ? `${config.security.rateLimitPerMinute}/min` : 'off'}**
- IP allowlist: **${config.security.allowedIps.length ? config.security.allowedIps.join(', ') : 'all'}**
- API key: **${config.security.apiKeyEnabled ? `header ${config.security.apiKeyHeader}` : 'off'}**
- Helmet: **${config.security.helmetEnabled ? 'on' : 'off'}**

${
  config.auth.enabled && config.auth.mode === 'create'
    ? `## Users table

If you do not already have a users table, run:

\`\`\`sql
${usersCreateSql(config)}\`\`\`
`
    : ''
}${
  selectedTables(config).some((t) => t.source === 'designed')
    ? `## Designed tables

This project includes tables created in the ApiForge canvas. Run the SQL files under \`sql/create-*.sql\` against your database before starting the API.
`
    : ''
}---
Forged with ApiForge.
`;

  return { path: 'README.md', content, language: 'markdown' };
}
