import type { GenerateConfig, GeneratedFile, TableMeta } from '@apiforge/shared';
import { authSqlFile } from '../common/auth-sql.js';
import { dockerFiles } from '../common/docker.js';
import { envExample } from '../common/env.js';
import { readmeFile } from '../common/readme.js';
import { kebabCase, routeName, selectedTables } from '../helpers.js';
import {
  generateAuthMiddleware,
  generateAuthRoutesExpress,
  generateDbTs,
  generateSecurityMiddleware,
  generateTableRouteExpress,
  nodePackageJson,
  nodeTsConfig,
} from './node-shared.js';

function swaggerTs(config: GenerateConfig, tables: TableMeta[]): GeneratedFile {
  const paths: Record<string, unknown> = {
    '/health': {
      get: {
        summary: 'Health check',
        responses: { '200': { description: 'OK' } },
      },
    },
  };

  if (config.auth.enabled) {
    paths['/auth/login'] = {
      post: {
        summary: 'Login',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                required: ['username', 'password'],
                properties: {
                  username: { type: 'string' },
                  password: { type: 'string' },
                },
              },
            },
          },
        },
        responses: { '200': { description: 'JWT token' } },
      },
    };
    if (config.auth.includeRegister) {
      paths['/auth/register'] = {
        post: {
          summary: 'Register',
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  required: ['username', 'password'],
                  properties: {
                    username: { type: 'string' },
                    password: { type: 'string' },
                  },
                },
              },
            },
          },
          responses: { '201': { description: 'Created' } },
        },
      };
    }
  }

  for (const table of tables) {
    const base = `/${routeName(table)}`;
    paths[base] = {
      get: { summary: `List ${table.name}`, responses: { '200': { description: 'OK' } } },
      post: { summary: `Create ${table.name}`, responses: { '201': { description: 'Created' } } },
    };
    paths[`${base}/{id}`] = {
      get: { summary: `Get ${table.name}`, responses: { '200': { description: 'OK' } } },
      put: { summary: `Update ${table.name}`, responses: { '200': { description: 'OK' } } },
      delete: { summary: `Delete ${table.name}`, responses: { '204': { description: 'Deleted' } } },
    };
  }

  const spec = {
    openapi: '3.0.3',
    info: {
      title: config.projectName,
      version: '1.0.0',
      description: 'Generated by ApiForge',
    },
    servers: [{ url: `http://localhost:${config.port}` }],
    components: config.auth.enabled
      ? {
          securitySchemes: {
            bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
          },
        }
      : {},
    paths,
  };

  return {
    path: 'src/swagger.ts',
    content: `import swaggerUi from 'swagger-ui-express';
import type { Express } from 'express';

export const openApiSpec = ${JSON.stringify(spec, null, 2)} as const;

export function setupSwagger(app: Express): void {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(openApiSpec));
}
`,
    language: 'typescript',
  };
}

function indexTs(config: GenerateConfig, tables: TableMeta[]): GeneratedFile {
  const imports = tables
    .map((t) => {
      const file = kebabCase(t.name);
      const varName = `${routeName(t).replace(/-/g, '_')}Router`;
      return `import ${varName} from './routes/${file}.js';`;
    })
    .join('\n');

  const mounts = tables
    .map((t) => {
      const varName = `${routeName(t).replace(/-/g, '_')}Router`;
      return `app.use('/${routeName(t)}', ${varName});`;
    })
    .join('\n');

  const authImport = config.auth.enabled
    ? `import authRouter from './routes/auth.js';\n`
    : '';
  const authMount = config.auth.enabled ? `app.use('/auth', authRouter);\n` : '';
  const swaggerImport = config.includeSwagger ? `import { setupSwagger } from './swagger.js';\n` : '';
  const swaggerSetup = config.includeSwagger ? `setupSwagger(app);\n` : '';

  return {
    path: 'src/index.ts',
    content: `import 'dotenv/config';
import express from 'express';
import { applySecurity } from './middleware/security.js';
${swaggerImport}${authImport}${imports}

const app = express();
const port = Number(process.env.PORT || ${config.port});

app.use(express.json());
applySecurity(app);

app.get('/health', (_req, res) => {
  res.json({ status: 'ok', service: '${config.projectName}' });
});

${authMount}${mounts}

${swaggerSetup}
app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(err);
  const message = err instanceof Error ? err.message : 'Internal Server Error';
  res.status(500).json({ error: message });
});

app.listen(port, () => {
  console.log(\`[${config.projectName}] listening on http://localhost:\${port}\`);
${config.includeSwagger ? `  console.log(\`Swagger UI: http://localhost:\${port}/api-docs\`);\n` : ''}});
`,
    language: 'typescript',
  };
}

export function generateNodeExpress(config: GenerateConfig): GeneratedFile[] {
  const tables = selectedTables(config);
  const files: GeneratedFile[] = [
    nodePackageJson(config, 'express'),
    nodeTsConfig(),
    envExample(config),
    readmeFile(config),
    generateDbTs(config),
    generateSecurityMiddleware(config),
    indexTs(config, tables),
  ];

  if (config.auth.enabled) {
    files.push(generateAuthMiddleware(), generateAuthRoutesExpress(config));
  }

  for (const table of tables) {
    files.push(generateTableRouteExpress(config, table));
  }

  if (config.includeSwagger) {
    files.push(swaggerTs(config, tables));
  }

  const sql = authSqlFile(config);
  if (sql) files.push(sql);

  files.push(...dockerFiles(config));
  return files;
}
